# creating array using numpy

In [2]:
import numpy as np
array= np. arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# indexing of array

In [3]:
array[0]

0

In [11]:
array[-3]

7

In [12]:
array[4]

4

In [13]:
array[-4]

6

In [14]:
array[-1]

9

# slicing of array

In [10]:
array[0:4]

array([0, 1, 2, 3])

In [16]:
array[-7:-2]

array([3, 4, 5, 6, 7])

In [6]:
array[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
array[:5]

array([0, 1, 2, 3, 4])

In [18]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# broadcasting

In [20]:
#broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. 

In [21]:
portion=array[5:]
portion

array([5, 6, 7, 8, 9])

In [25]:
portion[:]=10
portion

array([10, 10, 10, 10, 10])

In [26]:
array

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [61]:
array.shape

(10,)

In [29]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b  
c

array([ 10,  40,  90, 160])

# Matrix

In [27]:
#creating matrix using numpy
array2=np.array(([2,3,4,5],[3,4,5,6],[5,6,7,8]))
array2

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [6]:
matrix1 = np.array([[23,3,56,86,8,32,78,3,6,46,89,54,79,43,23,76]]).reshape(4,4)
matrix1

array([[23,  3, 56, 86],
       [ 8, 32, 78,  3],
       [ 6, 46, 89, 54],
       [79, 43, 23, 76]])

In [8]:
a = np.matrix('22 23; 23 24')
a

matrix([[22, 23],
        [23, 24]])

# matrix indexing

In [31]:
# to get 1st row 
array2[0]

array([2, 3, 4, 5])

In [47]:
array2[0:2]

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [49]:
array2[-3:-1]

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [50]:
array2[:]

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [117]:
# to get specific element 
array2[2][3]

8

# slicing of matrix

In [43]:
array2[1:,1:]

array([[4, 5, 6],
       [6, 7, 8]])

In [40]:
array2[:3,:2]

array([[2, 3],
       [3, 4],
       [5, 6]])

# brodcasting

In [53]:
portion=array2[0]
portion

array([2, 3, 4, 5])

In [54]:
portion[:]=1
portion

array([1, 1, 1, 1])

In [55]:
array2

array([[1, 1, 1, 1],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [62]:
array2.shape

(3, 4)

In [11]:
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]]) 
b = np.array([1,2,3])   
print ('First array:',a )
a    
print ('Second array:',b) 
b   
c=a + b
print ('First Array + Second Array',c)

First array: [[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
Second array: [1 2 3]
First Array + Second Array [[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


# Built in function for creating array 

In [19]:
#np.diag([1,2,3])
b=np.array(([1,2,3,4],[3,4,5,6],[5,6,7,8],[1,2,4,8]))
#np.diag(a)
b

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8],
       [1, 2, 4, 8]])

In [21]:
np.diag(b)

array([1, 4, 7, 8])

In [22]:
np.diag(b,k=1)

array([2, 5, 8])

In [104]:
b[np.diag_indices_from(b)] = 12
print(b)

[[12  2  3  4]
 [ 3 12  5  6]
 [ 5  6 12  8]
 [ 1  2  4 12]]


In [112]:
b[2][2]

12

In [113]:
a=np.diag([12,1,1])

In [114]:
a

array([[12,  0,  0],
       [ 0,  1,  0],
       [ 0,  0,  1]])

# zeros

In [27]:
#X = zeros(sz) returns an array of zeros where size vector sz defines size(X).
X = np.zeros(4)
X

array([0., 0., 0., 0.])

In [30]:
X=np.zeros((3,3))
X

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# ones

In [37]:
#ones() function is used to create a new array of given shape and type, filled with ones.

In [38]:
X=np.ones(7)
X

array([1., 1., 1., 1., 1., 1., 1.])

In [40]:
X=np.ones((2, 3))
X

array([[1., 1., 1.],
       [1., 1., 1.]])

# built in method 

In [42]:
# Import math Library
import math
# Return the square root of different numbers
x=(math.sqrt(9))
print(math.sqrt(25))
print(math.sqrt(16))
print(x)
print(type(x))

5.0
4.0
3.0
<class 'float'>


##log

In [44]:
# log(a,Base)
# Printing the log base e of 14
print ("Natural logarithm of 14 is : ", end="")
print (math.log(14))

# Printing the log base 5 of 14
print ("Logarithm base 5 of 14 is : ", end="")
print (math.log(14,5))


Natural logarithm of 14 is : 2.6390573296152584
Logarithm base 5 of 14 is : 1.6397385131955606


In [45]:
# log2(a)
# Printing the log base 2 of 14
print ("Logarithm base 2 of 14 is : ", end="")
print (math.log2(14))

Logarithm base 2 of 14 is : 3.807354922057604


##exp

In [5]:
#Exponential function 
#e = 2.7182 (e^X) 
import math
import numpy as np
a = 2
b = np.exp(3)
print (np.log(a))
print (np.log(b))

0.6931471805599453
3.0


# Python Math Module 

In [46]:
print(math.pi)

3.141592653589793


In [47]:
def circle_area(r):
    return math.pi*r**2
radius = 3
print("Area =", circle_area(radius))

Area = 28.274333882308138


In [48]:
print(math.tau)

6.283185307179586


In [49]:
print(math.e)

2.718281828459045


In [50]:
print(math.nan)
print(type(math.nan))

nan
<class 'float'>


In [51]:
print(math.inf)
print(-math.inf)

inf
-inf


In [52]:
p = 10.1
print(math.ceil(p))

11


In [53]:
q = 9.99
print(math.floor(q))

9


In [54]:
n = 5
print("{}! = {}".format(n, math.factorial(n)))

5! = 120


In [55]:
gcd = math.gcd(25, 120)
print(gcd)

5


In [56]:
print(math.fabs(-25))

25.0


In [57]:
deposit = 10000
interest_rate = 0.04
number_years = 5
final_amount = deposit * math.pow(1 + interest_rate, number_years)
print("The final amount after five years is", final_amount)

The final amount after five years is 12166.529024000001


In [58]:
print(math.exp(3))
print(math.pow(math.e, 3))

20.085536923187668
20.085536923187664


In [59]:
print(math.log(10))
print(math.log(10, 3))

2.302585092994046
2.095903274289385
